name: Build CI Core
on:
  push:
    paths:
      - 'ci_core_rs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ci_core_rs

      - name: Build CI Core
        run: cargo build --release --locked --manifest-path ci_core_rs/Cargo.toml

      - name: Release CI Core
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ci-core-latest
          name: CI Core Latest Build
          files: ci_core_rs/target/release/bahlil_ci_core
